In [2]:
import pandas as pd

denue = pd.read_csv('denue_inegi_14_.csv',index_col=False, encoding='latin-1')

denue.head()

C:\Users\arturo.carrillo\AppData\Local\Temp\ipykernel_22840\229190722.py:3: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  denue = pd.read_csv('denue_inegi_14_.csv',index_col=False, encoding='latin-1')

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,...,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta
0,8624390,14120112512000022000000000O3,ACUACULTORES LOS CASTRO,ACUACULTORES LOS CASTRO SC DE RL DE CV,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,CIRCUITO,DE LAS CAÑAS,CALLE,...,Campestre las Palomas [Fraccionamiento] ...,6940,13,3317429415.0,ELDOTE@HOTMAIL.COM,NaN,Fijo,20.820661,-103.446726,2019-11
1,8838371,14039112511000014000000000O4,ACUACULTURA DEL PACIFICO,ACUACULTURA DEL PACIFICO,112511,Camaronicultura,11 a 30 personas,CALLE,PABLO VALDEZ,CALLE,...,Guadalajara ...,1170,3,NaN,CONSTRULOGA@PRODIGY.NET.MX,NaN,Fijo,20.681686,-103.329962,2019-11
2,9233864,14095112512000022000000000O7,ACUIC0LA LA CABAÑA,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,CALLE,HIDALGO SUR,CALLE,...,Teuchitlán ...,010A,8,3841193710.0,NaN,NaN,Fijo,20.683360,-103.849741,2020-04
3,8341990,14095114119000082000000000O3,ACUICOLA DE VILLA CORONA,ACUICOLA DE VILLA CORONA,112512,"Piscicultura y otra acuicultura, excepto camar...",6 a 10 personas,CALLE,ALLENDE,CALLE,...,Villa Corona ...,0075,14,3331052902.0,NaN,NaN,Fijo,20.418737,-103.666418,2019-11
4,8908807,14079112512000011000000000U4,ACUÍCOLA EL DURAZNO,NaN,112512,"Piscicultura y otra acuicultura, excepto camar...",0 a 5 personas,NaN,SIN REFERENCIA,NaN,...,El Durazno ...,006A,800,NaN,NaN,NaN,Fijo,19.853656,-103.346905,2019-11

In [3]:
actividades = pd.read_excel('clusters_actividades.xlsx', sheet_name='actividades')

actividades.head()

   id_act                                          actividad
0  314110                Fabricación de alfombras y tapetes
1  321920  Fabricación de productos para embalaje y envas...
2  322210                  Fabricación de envases de cartón
3  323119    Impresión de formas continuas y otros impresos
4  324191       Fabricación de aceites y grasas lubricantes

In [4]:
denue.columns

Index(['id', 'clee', 'nom_estab', 'raz_social', 'codigo_act', 'nombre_act',
       'per_ocu', 'tipo_vial', 'nom_vial', 'tipo_v_e_1', 'nom_v_e_1',
       'tipo_v_e_2', 'nom_v_e_2', 'tipo_v_e_3', 'nom_v_e_3', 'numero_ext',
       'letra_ext', 'edificio', 'edificio_e', 'numero_int', 'letra_int',
       'tipo_asent', 'nomb_asent', 'tipoCenCom', 'nom_CenCom', 'num_local',
       'cod_postal', 'cve_ent', 'entidad', 'cve_mun', 'municipio', 'cve_loc',
       'localidad', 'ageb', 'manzana', 'telefono', 'correoelec', 'www',
       'tipoUniEco', 'latitud', 'longitud', 'fecha_alta'],
      dtype='object')

In [12]:
# Selección de variables del DENUE
datos = denue['id nom_estab raz_social codigo_act per_ocu telefono correoelec www nom_vial numero_ext cve_mun municipio latitud longitud'.split()]
datos = denue['id nom_estab raz_social codigo_act per_ocu telefono correoelec www nom_vial numero_ext cve_mun latitud longitud'.split()]

# Formato de letras mayúsculas
datos['nom_estab raz_social nom_vial municipio'.split()] = datos['nom_estab raz_social nom_vial municipio'.split()].apply(lambda x: x.str.title())
datos['correoelec www'.split()] = datos['correoelec www'.split()].apply(lambda x: x.str.lower())

datos.head()

C:\Users\arturo.carrillo\AppData\Local\Temp\ipykernel_22840\3554577468.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos['nom_estab raz_social nom_vial municipio'.split()] = datos['nom_estab raz_social nom_vial municipio'.split()].apply(lambda x: x.str.title())
C:\Users\arturo.carrillo\AppData\Local\Temp\ipykernel_22840\3554577468.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datos['correoelec www'.split()] = datos['correoelec www'.split()].apply(lambda x: x.str.lower())

,id,nom_estab,raz_social,codigo_act,per_ocu,telefono,correoelec,www,nom_vial,numero_ext,cve_mun,municipio,latitud,longitud
0,8624390,Acuacultores Los Castro,Acuacultores Los Castro Sc De Rl De Cv,112512,0 a 5 personas,3317429415.0,eldote@hotmail.com,NaN,De Las Cañas,71.0,120,Zapopan,20.820661,-103.446726
1,8838371,Acuacultura Del Pacifico,Acuacultura Del Pacifico,112511,11 a 30 personas,NaN,construloga@prodigy.net.mx,NaN,Pablo Valdez,606.0,39,Guadalajara,20.681686,-103.329962
2,9233864,Acuic0La La Cabaña,NaN,112512,0 a 5 personas,3841193710.0,NaN,NaN,Hidalgo Sur,66.0,95,Teuchitlán,20.683360,-103.849741
3,8341990,Acuicola De Villa Corona,Acuicola De Villa Corona,112512,6 a 10 personas,3331052902.0,NaN,NaN,Allende,76.0,114,Villa Corona,20.418737,-103.666418
4,8908807,Acuícola El Durazno,NaN,112512,0 a 5 personas,NaN,NaN,NaN,Sin Referencia,NaN,79,Gómez Farías,19.853656,-103.346905

In [13]:
# Filtrar actividades de clusters
datos = datos[datos['codigo_act'].isin(actividades['id_act'])]
datos.shape

(17197, 14)

In [14]:
# Exportar a CSV
datos.to_csv('denue_csv.csv', index=False, encoding="cp1252")

# Exportar a Excel
#datos.to_excel('datos_denue_excel.xlsx', index=False)